/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.camelapp.app

import net.camelapp.list.LinkedList

import static net.camelapp.utilities.StringUtils.join
import static net.camelapp.utilities.StringUtils.split
import static net.camelapp.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
